import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/Navigation/Navigation'
import { prisma } from '../lib/prisma'

interface LinkItem {
  id: number
  name: string
  route: string
}

interface Home {
  Links: LinkItem[]
}

const Home: NextPage<Home> = ({ Links }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation Links={Links}></Navigation>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const Links: LinkItem[] = await prisma.navigation.findMany({
    where: {
      enabled: true,
    },
    select: {
      id: true,
      name: true,
      route: true,
    },
    orderBy: {
      position: 'asc',
    },
  })
  return {
    props: { Links },
  }
}
